### ISSUE TITLE
libvchan.h includes <linux/types.h>

### ISSUE THREAD

**Issue by agacek** [SEL4PROJ/seL4_projects_libs#1]
`libvchan.h` includes `<linux/types.h>` which causes it to fail to compile in my environment. It seems like this include is only used to get `size_t` so it can be replaced by `<stddef.h>` instead.

**Comment by AdrianDanis** [comment]
This is quite curious. I've found another copy of libvchan [elsewhere](https://raw.githubusercontent.com/seL4/seL4_libs/01cbd4078e4531dff2e3e7e0cf606bc58c3e1799/libsel4vmm/include/vmm/libvchan.h) that seems to be identical except it `#include <stdint>` instead of `#include <linux/types.h>`. I'm happy to change this to anything that works for you in your environment.

**Comment by agacek** [comment]
In my case, this header is being pulled in for the build of components to run on seL4 so I only have the seL4 musllibc libraries.

**Comment by agacek** [comment]
Oops, it looks like GitHub was eating the headers in my original issue. I've updated it now. I was suggesting `<stddef.h>`, but `<stdint.h>` should work just as well.

**Comment by agacek** [comment]
Fixed by b59c1f1525e08dfbdc77b41eee917cdd862b0933
